name: API Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: api
      - name: Open Project
        run: cd api

      - name: Prepare Rust
        run: rustup target add windows-x86_64-pc-windows-gnu

      - name: Build
        run: cargo build --verbose --target windows-x86_64-pc-windows-gnu --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api/target/x86_64-pc-windows-gnu/release/api.exe