name: API Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v2
      with:
        toolchain: stable
        override: true
    - name: Install dependencies
      run: cargo install --path api
    - name: Build
      run: cd api && cargo build --release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: api
        path: api/target/debug/api.exe