name: API Build

on:
  push:
    branches: [ "api" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: api

      - name: Prepare Ubuntu
        run: sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Prepare Rust
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build
        run: cd api && cargo build --release --target x86_64-pc-windows-gnu --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: api/target/x86_64-pc-windows-gnu/release/api.exe

  create-package:
    name: Create Package
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: mx-monterrey-1.ocir.io
      IMAGE_NAME: salondebelleza/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: api

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.OCI_TENANCY }}/${{ env.IMAGE_NAME }}
          tags: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}