name: API Build

on:
  push:
    branches: [ "api" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: api

      - name: Prepare Ubuntu
        run: sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Prepare Rust
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build
        run: cd api && cargo build --release --target x86_64-pc-windows-gnu --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: api/target/x86_64-pc-windows-gnu/release/api.exe