name: API Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: api
      - name: Build
        run:
          cd api |
          rustup target add windows-x86_64-pc-windows-gnu |
          cargo build --verbose --target windows-x86_64-pc-windows-gnu --release |
          ls target/x86_64-pc-windows-gnu/release